apiVersion: apps/v1
kind: Deployment
metadata:
  name: fh-cd
  namespace: fh-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fh-cd
  template:
    metadata:
      labels:
        app: fh-cd
    spec:
      containers:
        - name: fh-cd
          image: re1coy/fh-cd:0.0.1
          ports:
            - containerPort: 8010
